version: '3.2'

services:

  pgsql:
    image: postgres:9.5
    environment:
     - POSTGRES_DB=mievento
     - POSTGRES_USER=mievento
     - POSTGRES_PASSWORD=mievento
    ports:
      - 54321:5432

  api:
    depends_on:
      - pgsql
    build: api
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_ENABLE_XDEBUG: 1

  backend:
    depends_on:
      - pgsql
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_ENABLE_XDEBUG: 1


