version: '3.2'

services:

#  pgsql:
#    image: postgres:9.5
#    environment:
#      - POSTGRES_DB=newtimes
#      - POSTGRES_USER=newtimes
#      - POSTGRES_PASSWORD=newtimes
#    ports:
#      - 54321:5432

  api:
#    depends_on:
#      - pgsql
    container_name: api
    build:
      - dockerfile: ./api/Dockerfile
    expose:
      - 80
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.apih.rule=Host(`apihits.rubrum.eu`)"
      - "traefik.http.routers.apih.entrypoints=http"
      - "traefik.http.routers.apih.service=apih"
      - "traefik.http.middlewares.apih-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.apih-redirectscheme.redirectscheme.permanent=false"
      - "traefik.http.routers.apih.middlewares=apih-redirectscheme"

      - "traefik.http.routers.apih-secure.rule=Host(`apihits.rubrum.eu`)"
      - "traefik.http.routers.apih-secure.entrypoints=https"
      - "traefik.http.routers.apih-secure.service=apih"
      - "traefik.http.routers.apih-secure.tls=true"
      - "traefik.http.routers.apih-secure.tls.certresolver=letsencrypt"

      - "traefik.http.services.apih.loadbalancer.server.port=80"
      - "traefik.http.services.apih.loadbalancer.server.scheme=http"
      - "traefik.http.services.apih.loadbalancer.passhostheader=true"


  backend:
#    depends_on:
#      - pgsql
    container_name: backendhits
    build:
      - dockerfile: ./backend/Dockerfile
    expose:
      - 80
    restart: always
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - ./docker/php/custom-config.ini:/usr/local/etc/php/conf.d/custom-config.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.backendh.rule=Host(`backendhits.rubrum.eu`)"
      - "traefik.http.routers.backendh.entrypoints=http"
      - "traefik.http.routers.backendh.service=backendh"
      - "traefik.http.middlewares.backendh-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.backendh-redirectscheme.redirectscheme.permanent=false"
      - "traefik.http.routers.backendh.middlewares=backendh-redirectscheme"

      - "traefik.http.routers.backendh-secure.rule=Host(`backendhits.rubrum.eu`)"
      - "traefik.http.routers.backendh-secure.entrypoints=https"
      - "traefik.http.routers.backendh-secure.service=backendh"
      - "traefik.http.routers.backendh-secure.tls=true"
      - "traefik.http.routers.backendh-secure.tls.certresolver=letsencrypt"

      - "traefik.http.services.backendh.loadbalancer.server.port=80"
      - "traefik.http.services.backendh.loadbalancer.server.scheme=http"
      - "traefik.http.services.backendh.loadbalancer.passhostheader=true"


networks:
  default:
    external:
      name: proxy